# Generated by Django 4.2.4 on 2023-09-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can_manage_author', 'add edit delete author'),)},
        ),
    ]
